name: scene_demo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0-1.0.pre.242"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  vector_math: ^2.1.4
  flutter_scene: ^0.11.0
  flutter_scene_importer: ^0.11.0
  gamepads: ^0.1.1
  json_annotation: ^4.8.1
  flutter_animate: ^4.5.0
  flutter_soloud: ^1.2.5
  hooks: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/dash.png
    - assets/potion.ogg
    - assets/machine.ogg
    - assets/pickupCoin2.wav
    - assets/shatter3.ogg
    - assets/jump.wav

    # Imported models.
    - build/models/
